// English text for every page other than the landing page. pages.js adds the links.
export default {
  founder: {
    title: 'Nour Saif, Founder and CEO',
    description: 'Nour Saif is the founder and CEO of Nuralix, building living digital health twins for proactive family care.',
    name: 'Nour Saif',
    role: 'Founder and CEO of Nuralix',
    mission:
      'Nuralix was created to help families stay closer to the health of the people they love. Care should be intelligent, transparent, and human, from the home to the hospital.',
    aboutTitle: 'About Nour',
    about:
      'Nour Saif is a health-tech founder focused on proactive, AI-driven care for families across the Middle East and diaspora communities. She founded Nuralix to close the gap between hospital-grade monitoring and the daily reality of caring for aging parents, chronic conditions, and loved ones at a distance.',
    basedIn: 'Based in',
    place: 'New York, NY',
    email: 'Email',
    linkedIn: 'LinkedIn',
  },

  contact: {
    title: 'Get in touch.',
    metaTitle: 'Contact',
    description: 'Get in touch with the Nuralix team about the family health twin, partnerships, SDK integration, or press enquiries.',
    lede: "Have questions about Nuralix, partnerships, or SDK integration? We'd love to hear from you.",
    place: 'Based in New York, New York',
  },

  investors: {
    metaTitle: 'Investors and partners',
    description: 'Nuralix is building the AI infrastructure for family health observability. Explore our roadmap, traction, and partnership opportunities.',
    title: 'Building the AI infrastructure for family health observability.',
    lede: 'Nuralix is positioned at the intersection of AI health agents, digital twins, remote patient monitoring, and hospital intelligence, a category-defining opportunity in proactive care.',
    stats: [
      { value: '12+', label: 'Health signal categories' },
      { value: '2', label: 'Languages supported (AR + EN)' },
      { value: '17', label: 'Product modules across the platform' },
      { value: '100%', label: 'Consent-based and privacy-first' },
    ],
    tractionTitle: 'Traction and momentum',
    traction: [
      { label: 'Unified consumer account', value: 'Live', note: 'One identity across Nuralix Health and Health Hub' },
      { label: 'Founding partner pipeline', value: 'In discussions', note: 'Senior care and clinical pilots' },
      { label: 'Geographic focus', value: 'MENA + Diaspora', note: 'Expanding globally' },
      { label: 'Funding stage', value: 'Pre-seed', note: 'Engaging strategic investors' },
    ],
    roadmapTitle: 'Product roadmap',
    phases: [
      {
        title: 'Now',
        status: 'Live',
        items: [
          'Personal health digital twin',
          'Family and caregiver dashboard',
          'Nora AI companion (AR + EN)',
          'Genetics upload and analysis',
          'Wearable and symptom integrations',
          'Medication, fall and alert system',
        ],
      },
      {
        title: 'Next',
        status: 'In build',
        items: [
          'Uploaded medical reports and labs',
          'Risk intelligence and trend analytics',
          'Expanded wearable integrations',
          'Caregiver coordination tools',
        ],
      },
      {
        title: 'Future',
        status: 'Roadmap',
        items: [
          'Camera-based temperature screening',
          'Hospital facial recognition',
          'Patient identity matching at intake',
          'Clinical partner dashboard',
          'Population health insights',
        ],
      },
    ],
    close: 'Investor decks, partner briefs, and pilot opportunities available on request.',
    talk: 'Talk to the founder',
    partner: 'Partner with us',
  },

  family: {
    metaTitle: 'Family',
    description: 'One place for your own health information and the relatives who have chosen to share theirs with you.',
    title: 'Your health and your family, one sign-in.',
    lede: 'Nuralix Health gives you one place for your own information and the relatives who have chosen to share health information with you.',
    open: 'Open Family in Health Hub',
    create: 'Create your Nuralix account',
    stepsTitle: 'Before web access',
    steps: [
      'Create or sign in to your Nuralix account once.',
      'Open Family and accept or send an invitation.',
      'Confirm the sharing permissions for each family member.',
    ],
    points: [
      { title: 'Create one account', body: 'Create your Nuralix account on the web or in the mobile app.' },
      { title: 'Connect your family', body: 'Invite relatives and choose exactly what each person can share.' },
      { title: 'Monitor with context', body: 'Review shared wellness, alerts, medications, and recent changes on web or mobile.' },
    ],
    staff: ['Hospital staff should use the ', 'Provider Portal', '.'],
  },

  genetics: {
    metaTitle: 'Genetics',
    description: 'What Nuralix checks in your DNA: 46 conditions, 84 traits, medication response and carrier status.',
    title: 'Everything Nuralix checks in your DNA.',
    lede: 'From one saliva kit, or a DNA file you already have.',
    counts: ['conditions', 'traits', 'medication response levels', 'conditions with targeted therapies'],
    conditionsTitle: 'Conditions',
    conditionsBody: 'Your genetic risk compared with average, in six areas.',
    traitsTitle: 'Traits',
    traitsBody: 'What your DNA says about everyday habits.',
    medicationTitle: 'Medication response',
    medicationBody: 'Each relevant medication gets one of four levels, with a CPIC clinical-evidence level.',
    therapiesTitle: 'Therapies by gene and disease',
    therapiesBody: 'When a confirmed pathogenic variant is found, Nuralix can surface approved targeted and gene therapies for discussion with a clinician.',
    closeTitle: 'Start with a kit or a file.',
    order: 'Order your kit · $249',
    analysis: 'Genetic analysis · $49.99',
    formats: 'Upload a 23andMe export (ZIP or TXT), an AncestryDNA TXT file, or a VCF file.',
    fine: 'All outputs are informational health insights, not medical diagnoses or prescriptions. Polygenic risk and trait scores are marker-panel based and reported as research-informed. Targeted therapies surface only from a confirmed pathogenic variant and generally require a matching diagnosis. A qualified clinician should confirm findings and prescribe any treatment.',
  },

  legal: { notice: null },

  auth: {
    description: 'One secure account opens Health Hub on the web and your Nuralix mobile app.',
    staff: ['Hospital staff use the separate ', 'Provider Portal', '.'],
    email: 'Email',
    emailExample: 'you@example.com',
    password: 'Password',
    newPassword: 'New password',
    confirmPassword: 'Confirm password',
    passwordHint: 'Use 8–128 characters with at least one letter and one number.',
    signIn: {
      title: 'Sign in',
      lede: 'Use the same email and password you use in the Nuralix mobile app.',
      checking: 'Checking your Nuralix account…',
      forgot: 'Forgot password?',
      submit: 'Sign in',
      busy: 'Signing in…',
      newHere: 'New to Nuralix?',
      create: 'Create a free account',
      failed: "We couldn't sign you in. Check your email and password and try again.",
    },
    signUp: {
      title: 'Create your account',
      lede: 'One account for Nuralix Health, Health Hub on the web, and the mobile app.',
      firstName: 'First name',
      lastName: 'Last name',
      sex: 'Sex at birth',
      sexHint: 'Used to personalize relevant health and genetics insights.',
      select: 'Select',
      // The account service expects these English values; the labels are what the visitor sees.
      sexes: [{ value: 'Male', label: 'Male' }, { value: 'Female', label: 'Female' }],
      born: 'Date of birth',
      agree: ['I agree to the ', 'Terms of Service', ' and ', 'Privacy Policy', '.'],
      submit: 'Create a free account',
      busy: 'Creating account…',
      haveAccount: 'Already have an account?',
      signIn: 'Sign in',
      failed: "We couldn't create your account. Please try again.",
      sentTitle: 'Check your email',
      sent: ['We sent a verification link to ', '. Verify your email, then sign in with this same account everywhere Nuralix is available.'],
      proceed: 'Continue to sign in',
    },
    forgot: {
      title: 'Reset your password',
      lede: 'Enter your email and we will send you a reset link.',
      submit: 'Send reset link',
      busy: 'Sending…',
      back: 'Back to sign in',
      failed: "We couldn't send the reset email. Please try again.",
      sentTitle: 'Check your email',
      sent: ['If an account exists for ', ', a password-reset link is on its way.'],
    },
    reset: {
      title: 'Choose a new password',
      lede: 'This updates the password used across Nuralix.',
      submit: 'Update password',
      busy: 'Updating…',
      failed: 'This reset link is invalid or expired. Request a new one.',
      doneTitle: 'Password updated',
      signIn: 'Sign in',
      badLinkTitle: 'This reset link is invalid or expired.',
      badLink: 'Request a new one to choose a password.',
      requestNew: 'Request a new link',
    },
    verify: {
      metaTitle: 'Email verification',
      verifiedTitle: 'Email verified',
      verified: 'You can now sign in once and continue to Nuralix Health on the web or mobile app.',
      expiredTitle: 'Verification link expired',
      expired: 'Request a new verification email by signing in again.',
      proceed: 'Continue to sign in',
    },
    // Messages raised in English by lib/auth.js. Other languages map them here.
    messages: {},
  },
};
